### ISSUE TITLE
pythreejs-0.4.2 seems not on pypi 

### ISSUE THREAD

**Issue by stonebig** [jupyter-widgets/pythreejs#155]
normal ?

**Comment by SylvainCorlay** [comment]
That is right. The 0.4.2 (on the 0.4.x branch) includes an update of the three.js javascript package to be compatible with ipyvolume in JupyterLab.

I noticed an issue which might be due to this after I tagged the version. I will push on pypi if everything is ok.

**Comment by vidartf** [comment]
@SylvainCorlay Do we still want to do something here, or should we simply close?

**Comment by SylvainCorlay** [comment]
oh I thought I had fixed this a long time ago. I should probably push this manually.

**Comment by vidartf** [comment]
@SylvainCorlay did you make any progress? Or should we simply skip it?

**Comment by SylvainCorlay** [comment]
Hum not sure it is worth it...
