### ISSUE TITLE
Move to jupyter-widgets org

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/pythreejs#179]
@vidartf - what do you think about moving pythreejs to the jupyter-widgets org?

**Comment by vidartf** [comment]
I'm fine with it 👍

**Comment by SylvainCorlay** [comment]
@vidartf do you have the privileges to do it?

**Comment by jasongrout** [comment]
When do you want to transfer it? Today?

**Comment by vidartf** [comment]
I'll transfer it when I have the time to also make sure CI/RTD/links follows. Probably tomorrow or Monday!

**Comment by vidartf** [comment]
Moved, starting cleanup effort.

**Comment by SylvainCorlay** [comment]
> Let me know if you know of any other things that should be updated!

@vidartf you may want to update the widgets page on jupyter.org with the new project location.

**Comment by vidartf** [comment]
What should be done with the flight-sim repo?

**Comment by SylvainCorlay** [comment]
Oh, right, I should fix it and move it to `jupyter-widgets` .

**Comment by SylvainCorlay** [comment]
@vidartf can you add me as an owner of the pythreejs RTD project? I was just setting up the one for ipyleaflet, so I could do this one as well.
