### ISSUE TITLE
return from exec_three_obj_method

### ISSUE THREAD

**Issue by tingelst** [jupyter-widgets/pythreejs#193]
How can I capture the return value when calling `exec_three_obj_method`?

**Comment by vidartf** [comment]
There is currently not an official API for this (suggestions / PR welcome). As a workaround / hack, you can override the class / instance method ` def _on_ret_val(self, method_name, ret_val): ...`. Note that this gets called asynchronously (i.e. possibly after the cell has finished executing), so you need to be mindful of this!

**Comment by tingelst** [comment]
Thank you! Is this the reason why `matrixWorld` isn't updated directly when calling `exec_three_obj_method('updateMatrixWorld')` in the same cell?

**Comment by vidartf** [comment]
Yes, all syncs / updates are asynchronous. If you set up an traitlets change notification on the `matrixWorld` property, you should be notified when it changes.

**Comment by tingelst** [comment]
Takk!
