### ISSUE TITLE
About "Pythreejs" equivalent implementation in pure "Three.js" javascript.

### ISSUE THREAD

**Issue by KelSolaar** [jupyter-widgets/pythreejs#202]
Hi,

I was wondering what was the equivalent implementation of this `pythreejs` code in pure `Three.js` javascript:

```python
from IPython.display import display
from pythreejs import *

width=640
height=480

vertices = [[0.3, 0.6, 0.715], [0.313, 0.329, 0.0], [0.313, 0.329, 0.0], [0.64, 0.33, 0.213], [0.64, 0.33, 0.213], [0.419, 0.505, 0.928], [0.419, 0.505, 0.928], [0.3, 0.6, 0.715], [0.225, 0.329, 0.787], [0.15, 0.06, 0.072], [0.15, 0.06, 0.072], [0.321, 0.154, 0.285], [0.321, 0.154, 0.285], [0.313, 0.329, 1.0], [0.313, 0.329, 1.0], [0.225, 0.329, 0.787], [0.64, 0.33, 0.213], [0.313, 0.329, 0.0], [0.313, 0.329, 0.0], [0.15, 0.06, 0.072], [0.15, 0.06, 0.072], [0.321, 0.154, 0.285], [0.321, 0.154, 0.285], [0.64, 0.33, 0.213], [0.419, 0.505, 0.928], [0.3, 0.6, 0.715], [0.3, 0.6, 0.715], [0.225, 0.329, 0.787], [0.225, 0.329, 0.787], [0.313, 0.329, 1.0], [0.313, 0.329, 1.0], [0.419, 0.505, 0.928], [0.15, 0.06, 0.072], [0.313, 0.329, 0.0], [0.313, 0.329, 0.0], [0.3, 0.6, 0.715], [0.3, 0.6, 0.715], [0.225, 0.329, 0.787], [0.225, 0.329, 0.787], [0.15, 0.06, 0.072], [0.321, 0.154, 0.285], [0.64, 0.33, 0.213], [0.64, 0.33, 0.213], [0.419, 0.505, 0.928], [0.419, 0.505, 0.928], [0.313, 0.329, 1.0], [0.313, 0.329, 1.0], [0.321, 0.154, 0.285]]
colours = [u'#00ff00', u'#000000', u'#000000', u'#ff0000', u'#ff0000', u'#ffff00', u'#ffff00', u'#00ff00', u'#00ffff', u'#0000ff', u'#0000ff', u'#ff00ff', u'#ff00ff', u'#ffffff', u'#ffffff', u'#00ffff', u'#ff0000', u'#000000', u'#000000', u'#0000ff', u'#0000ff', u'#ff00ff', u'#ff00ff', u'#ff0000', u'#ffff00', u'#00ff00', u'#00ff00', u'#00ffff', u'#00ffff', u'#ffffff', u'#ffffff', u'#ffff00', u'#0000ff', u'#000000', u'#000000', u'#00ff00', u'#00ff00', u'#00ffff', u'#00ffff', u'#0000ff', u'#ff00ff', u'#ff0000', u'#ff0000', u'#ffff00', u'#ffff00', u'#ffffff', u'#ffffff', u'#ff00ff']
geometry = Geometry(vertices=vertices, colors=colours)
wireframe = LineSegments(geometry=geometry, material=LineBasicMaterial(vertexColors='VertexColors'))

scene = Scene(children=[wireframe])
camera = PerspectiveCamera(
        position=[-3, 3, 3], fov=20, aspect=width / height)
controls = OrbitControls(controlling=camera)

Renderer(
        camera=camera,
        scene=scene,
        controls=[controls],
        width=width,
        height=height,
        antialias=True)
```

I did try  few things but no cigar if I don't provide faces in a way or another, so it makes me wonder what is going on under the hood in `pythreejs`. Interestingly, the [Three.js Geometry](https://threejs.org/docs/#api/core/Geometry) class constructor does not take any arguments while the `pythreejs` version does.

Is there a document explaining how the binding is performed? I did not spend too much time looking at the code but it was not crystal clear.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Hi,

I should have said *indices* instead of *faces* (even though they ultimately are represented with *indices*). I found an example on how to do that in pure JS: https://stackoverflow.com/a/35179514 and it turns out you don't necessarily need to set the *indices* when fiddling with it either. I'm not sure what I did incorrectly.

>  if you can give me a few more specific questions I can better answer concisely.

In that case I was wondering how 
```python
wireframe = LineSegments(geometry=geometry, material=LineBasicMaterial(vertexColors='VertexColors'))
```
was translated to the equivalent in `three.js`.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Right and I suppose `geometry` is just the equivalent `three.js` `Geometry` class and not `BufferGeometry`. vertexColors works for `LineBasicMaterial` btw!

**Comment by vidartf** [comment]
>Right and I suppose geometry is just the equivalent three.js Geometry class and not BufferGeometry

`Geometry` and `BufferGeometry` are both available in pythreejs, and distinct.

> vertexColors works for LineBasicMaterial btw!

Ah yes, I misread the code. Nevermind :)

**Comment by KelSolaar** [comment]
Thanks! Closing this one 👍
