### ISSUE TITLE
Version > 2.0.0 raises an error on jupyterlab

### ISSUE THREAD

**Issue by hadim** [jupyter-widgets/pythreejs#230]
Please see the thread for this details: https://github.com/maartenbreddels/ipyvolume/issues/201#issuecomment-435853281

Error:

```
Module jupyter-threejs, semver range ^2.0.2 is not registered as a widget module
```

Here is a binder session that reproduce the issue: https://mybinder.org/v2/gh/hadim/binder-sandbox/master?urlpath=lab/tree/notebooks/ipyvolume-bug.ipynb

**Comment by hadim** [comment]
Thanks, @vidartf.

You can ping me here when the JS and PY packages are released to npm/conda so I can test.

**Comment by vidartf** [comment]
@hadim Should be up by now!

**Comment by hadim** [comment]
It works like a charm!

Small suggestion: you should tag the release you do in Git, https://github.com/jupyter-widgets/pythreejs/releases.

**Comment by michaelaye** [comment]
This seems to have regressed for pythreejs 2.1.1 (or jupyterlab 2.x?)

<img width="731" alt="Screenshot 2020-03-13 17 54 10" src="https://user-images.githubusercontent.com/69774/76669976-b6b18680-6553-11ea-8fa1-857a570af4aa.png">

**Comment by hadim** [comment]
This is a very typical JLab version incompatibility version error so probably due to JLab 2.0. I saw the same kind of error with other extensions.

**Comment by michaelaye** [comment]
yeah, works fine when switching to notebook.

**Comment by vidartf** [comment]
Yes, pythreejs has not yet added support for lab 2. WIP
