### ISSUE TITLE
Examples: radialSegments -> radiusSegments

### ISSUE THREAD

**Issue by wstomv** [jupyter-widgets/pythreejs#251]
In https://github.com/jupyter-widgets/pythreejs/blob/952ab13c21ab19425328083f126bd51e1dc397ea/examples/Geometries.ipynb#L173 and other places, `radialSegments` appears, but this should be `radiusSegments`.

**Comment by vidartf** [comment]
Thanks for the report! There is definitely an error here, but the three.js docs/code should be considered the source of truth here. I'll add this to #253 shortly!

**Comment by vidartf** [comment]
Xref: https://github.com/mrdoob/three.js/pull/13509
