### ISSUE TITLE
PlainGeometry missing in 2.0.2

### ISSUE THREAD

**Issue by PBrockmann** [jupyter-widgets/pythreejs#254]
I cannot instantiate a PlainGeometry with last 2.0.2 release.

<pre>
geom = PlainGeometry(vertices=[[0,0,0],[30,0,0],[30,30,0]],
faces=[[0,1,2]],
colors = ['red', 'blue', 'green'])
mesh = Mesh(geometry=geom, material=BasicMaterial(color='blue'))
scene = Scene(children=[mesh,AmbientLight(color='#cccccc')])
c = PerspectiveCamera(position=[0, 0, 100], fov = 40, aspect = 6/4, near = 1, far = 1000)
renderer = Renderer(camera=c, scene = scene, controls=[OrbitControls(controlling=c)])
display(renderer)
</pre>

should work. I get
`
NameError: name 'PlainGeometry' is not defined
`

**Comment by vidartf** [comment]
The `Plain[Buffer]Geometry` classes was renamed when going to 1.x, in order to more closely align with the three.js API: https://pythreejs.readthedocs.io/en/stable/installing.html#upgrading-to-1-x

**Comment by vidartf** [comment]
I also see that we should link to the docs from the README...

**Comment by PBrockmann** [comment]
An example with a face-colored geometry would help me a lot.
As the cube in https://stemkoski.github.io/Three.js/Vertex-Colors.html

**Comment by vidartf** [comment]
You could have a look at this example: https://render.githubusercontent.com/view/ipynb?commit=645ea6bea758555978f83bd0004ce561fa58d99c&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6a7570797465722d776964676574732f707974687265656a732f363435656136626561373538353535393738663833626430303034636535363166613538643939632f6578616d706c65732f4578616d706c65732e6970796e62&nwo=jupyter-widgets%2Fpythreejs&path=examples%2FExamples.ipynb&repository_id=15400194&repository_type=Repository#Buffer-Geometries

**Comment by vidartf** [comment]
Or if you still want to use the old `Geometry` type, the previous paragraph to that example can be helpful (I would say the BufferGeometry code is cleaner though).

**Comment by PBrockmann** [comment]
Thanks but... 
I would like face colors.

![image](https://user-images.githubusercontent.com/5402758/55244529-a53b7580-5241-11e9-8515-d4d8f7ae05b3.png)

**Comment by PBrockmann** [comment]
This line is obscur.

```
# Map the vertex colors into the 'color' slot of the faces
faces = [f + [None, [vertexcolors[i] for i in f], None] for f in faces]
```

```
vertices = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
]

faces = [
    [0, 1, 3],
    [0, 3, 2],
    [0, 2, 4],
    [2, 6, 4],
    [0, 4, 1],
    [1, 4, 5],
    [2, 3, 6],
    [3, 7, 6],
    [1, 5, 3],
    [3, 5, 7],
    [4, 6, 5],
    [5, 6, 7]
]

vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']

facescolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
               '#00ffff', '#ff00ff', '#ffff00', '#ffffff',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']

# Map the vertex colors into the 'color' slot of the faces
faces = [f + [None, [vertexcolors[i] for i in f], None] for f in faces]

# Create the geometry:
cubeGeometry = Geometry(
    vertices=vertices,
    faces=faces
)

# Create a mesh. Note that the material need to be told to use the vertex colors.
mesh = Mesh(
    geometry=cubeGeometry,
    material=MeshBasicMaterial(vertexColors='FaceColors'),
    position=[-0.5, -0.5, -0.5],   # Center the cube
)

scene = Scene(children=[mesh], background="#cccccc")

c = PerspectiveCamera(position=[3, 3, 3])

rendererCube = Renderer(camera=c,
                        scene=scene, 
                        controls=[OrbitControls(controlling=c)])

display(rendererCube)
```

**Comment by PBrockmann** [comment]
Got it. 
![image](https://user-images.githubusercontent.com/5402758/55278588-9cfd3c00-530e-11e9-92e8-aee998fd5c56.png)

The faces list should be as
`
[0, 1, 3, None, '#a4fcdd', None]
`
Have to understand why 2 None have to be inserted.

So replace in the previous pythreejs python code:
`
faces = [f + [None, [vertexcolors[i] for i in f], None] for f in faces]
`
by
`
faces = [faces[i] + [None, rand_color.generate()[0], None] for i in range(0,len(faces))]
`

So code becomes:
```
vertices = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
]

faces = [
    [0, 1, 3],
    [0, 3, 2],
    [0, 2, 4],
    [2, 6, 4],
    [0, 4, 1],
    [1, 4, 5],
    [2, 3, 6],
    [3, 7, 6],
    [1, 5, 3],
    [3, 5, 7],
    [4, 6, 5],
    [5, 6, 7]
]

vertexcolors = ['#000000', '#0000ff', '#00ff00', '#ff0000',
                '#00ffff', '#ff00ff', '#ffff00', '#ffffff']

faces = [faces[i] + [None, rand_color.generate()[0], None] for i in range(0,len(faces))]

# Create the geometry:
cubeGeometry = Geometry(
    vertices=vertices,
    faces=faces
)

# Create a mesh. Note that the material need to be told to use the vertex colors.
mesh = Mesh(
    geometry=cubeGeometry,
    material=MeshBasicMaterial(vertexColors='FaceColors'),
    position=[-0.5, -0.5, -0.5],   # Center the cube
)

scene = Scene(children=[mesh], background="#cccccc")

c = PerspectiveCamera(position=[3, 3, 3])

rendererCube = Renderer(camera=c,
                        scene=scene, 
                        controls=[OrbitControls(controlling=c)])

display(rendererCube)
```

**Comment by PBrockmann** [comment]
Is there a way to optimize this simple example this by using BufferGeometry rather than Geometry ?
in fact, my real project is to display and update more than 360x180 quads (made from 2 triangles).

As with this mesh (2 deg x 2 deg)
![image](https://user-images.githubusercontent.com/5402758/55339085-4aed1f80-54a2-11e9-8c5b-050f6b08b08a.png)

BTW, a 1deg x 1deg mesh is not displayed (https://github.com/jupyter-widgets/pythreejs/issues/219)

**Comment by vidartf** [comment]
Using a BufferGeometry should normally be much more performant, both in sync and in rendering. It might be slightly more complex to understand how to set up the arrays correctly though. Hopefully, there is a relevant JS example out there.

**Comment by PBrockmann** [comment]
Could you point me this exemple, one with a FacesColor mode ?

**Comment by PBrockmann** [comment]
Ok, I have figured out how to instantiate a BufferGeometry by transforming a classic Geometry with the from_geometry() method and then checking needed attributes.

```
geometry = Geometry(vertices=vertices, faces=faces)
bufferGeometry = BufferGeometry()
a = bufferGeometry.from_geometry(geometry)
a.attributes
```

**Comment by PBrockmann** [comment]
Comparison between the 2 codes are available from https://gist.github.com/PBrockmann/ddd0d5ad4205f153e1287be3a9a68078

I suppose the BufferGeometry procures a better display.
Note that I have to set 6 times each color values to display face colored quads. Quad primitives is there crudelly missing.

I still have the limititations of the number of vertex (1deg x 1deg does not display anything).
I am sti

**Comment by PBrockmann** [comment]
Also would need to know how to update colors ?
WIth a Geometry(vertices=vertices,faces=faces), changing faces update the object.

Now with a 
```
BufferGeometry(attributes=dict(
        position = BufferAttribute(p),
        color = changeColors()
))
```
No change are done.

**Comment by PBrockmann** [comment]
Thanks to @vidartf for the solution

``geometry.attributes['color'] = new_cList``
should be
``geometry.attributes['color'].array = new_cList``

Correct notebook is available from https://gist.github.com/PBrockmann/f155a779382e2b8dec7543f3466e0798

I think this issue can be closed.
