### ISSUE TITLE
JupyterLab 1.0 update

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/pythreejs#281]
I think for this to work in JupyterLab 1.0, this line: https://github.com/jupyter-widgets/pythreejs/blob/4d2f2fa828c7184dc5a7d539ac879fbe2eb61375/js/package.json#L37

needs to be changed to
```
"@jupyter-widgets/base": "^1.2.5 || ^2",
```

**Comment by vidartf** [comment]
There are some other widget dependencies that needs to be updated first as well. They are in the pipeline.

**Comment by jasongrout** [comment]
Just curious, what else needs to be updated?

**Comment by vidartf** [comment]
jupyter-dataserializers

**Comment by vidartf** [comment]
Updated as a patch release! Please open issues if there any problems with it.
