### ISSUE TITLE
Bounding box method not working

### ISSUE THREAD

**Issue by jmmshn** [jupyter-widgets/pythreejs#282]
Hi,
Thank you for this incredibly useful package!
I have (perpaps a silly) question I'm having problems getting the bounding box of a object to display.

Below is a minimal example of the problem. The output is a box with zeros for the max and min boundary.  Please let me know if I am misunderstanding something.
Thanks!

```
from pythreejs import *
import numpy as np
from IPython.display import display
from ipywidgets import HTML, Text, Output, VBox
from traitlets import link, dlink
ob3 = Object3D(name='root')
ball = Mesh(geometry=SphereGeometry(radius=1, widthSegments=32, heightSegments=24), 
            material=MeshLambertMaterial(color='red'),
            position=[2, 1, 0])
ball2 = Mesh(geometry=SphereGeometry(radius=1, widthSegments=32, heightSegments=24), 
            material=MeshLambertMaterial(color='red'),
            position=[-2, 1, 0])

ob3.add(ball)
ob3.add(ball2)
ob3

box = Box3()
box.exec_three_obj_method('setFromObject', ob3) # this is the line I'm not sure about 
print(box)
```

**Comment by vidartf** [comment]
In general, calling methods is *asynchronous*, so the results will not be immediately available. As such, it should be considered an advanced feature that will complicate you logic quite a bit. As such, you might be better off using something else to set the dimensions of `box`.

If you still want to use `setFromObject` asynchronously, your best bet would probably be to [observe](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Events.html#Traitlet-events) the scale of `box`, and then react to that.

**Comment by jmmshn** [comment]
OK thanks for the quick response! I will do the computation of the bounding box elsewhere then.

**Comment by vidartf** [comment]
Closing as answered then. Feel free to comment further if needed.
