### ISSUE TITLE
Would like to disable mesh preview mouse controls

### ISSUE THREAD

**Issue by mstanley103** [jupyter-widgets/pythreejs#296]
I'm trying to use pythreejs to implement a simple display that will eventually rotate as a function of a rotation measured by an external sensor board.  A simple preview of my imported mesh works great except for one thing: it's sensitive to mouse inputs, which can be used to rotate or pan the image.  I would like to turn off that function and control the rotation explicitly - which I already know how to do using a quaternion.  Building up a full scene with lights, camera, etc can do the job, but seems significantly slower and is more than I need.  Can anyone advise if what I'm trying to do is possible?  Again, I just want to disable the mouse controls on the mesh preview.  My example is attached as a zip.

[copter.zip](https://github.com/jupyter-widgets/pythreejs/files/3834238/copter.zip)

**Comment by vidartf** [comment]
Having a simple function that sets up scene/renderer for you would probably be your best bet. You mention that it seems "significantly" slower, so I'm curious what kind of creation times you are seeing.

**Comment by mstanley103** [comment]
Thanks for the quick response.  I'll have to set up an apples to apples comparison to see if I can quantify response times.  My current scene definition is probably more complex than it needs to be.  I've spent a lot of time trying to get it (full scene/renderer definition) right, when in fact the preview is exactly what I want with the exception of the mouse issue.

**Comment by vidartf** [comment]
Closing as stale.
