### ISSUE TITLE
ArrowHelper direction bug

### ISSUE THREAD

**Issue by Boomer91** [jupyter-widgets/pythreejs#323]
Hi, thanks for developing this awesome tool!

Arrows do render now, but there seems to be a bug with the direction argument. See minimal example below. Unit directions work fine, but e.g. dir = (1,1,1) renders a dir = (1,0,0) vector.

Thanks,
Cyriel

```python
from pythreejs import *

scene = Scene()

camera = PerspectiveCamera(position=[15, 0, -2], up=[0,0,-1])
scene.add(camera)

control = OrbitControls(controlling=camera, maxDistance=100)

renderer = Renderer(camera=camera, scene=scene,
controls=[control],
width=1000, height=800
)

axes = AxesHelper(size=1)
scene.add(axes)

arrow = ArrowHelper(
        dir=[1,0,0],
        origin=[1,0,0],
        length=3,
        color='red',
        headLength=None,
        headWidth=None,
)
scene.add(arrow)

arrow = ArrowHelper(
        dir=[0,1,0],
        origin=[1,0,0],
        length=3,
        color='green',
        headLength=None,
        headWidth=None,
)
scene.add(arrow)

arrow = ArrowHelper(
        dir=[0,0,1],
        origin=[1,0,0],
        length=3,
        color='blue',
        headLength=None,
        headWidth=None,
)
scene.add(arrow)

arrow = ArrowHelper(
        dir=[1,1,1],
        origin=[1,0,0],
        length=3,
        color='black',
        headLength=None,
        headWidth=None,
)
scene.add(arrow)

scene.add(AmbientLight(intensity=0.3))

renderer
```

_Originally posted by @Boomer91 in https://github.com/jupyter-widgets/pythreejs/issues/258#issuecomment-625880930_

**Comment by vidartf** [comment]
Please refer to the [threejs documentation](https://threejs.org/docs/#api/en/helpers/ArrowHelper). It states that `dir` must be a unit vector. Does it work if you set `dir=[1./3., 1./3., 1./3.]` ?

> dir -- direction from origin. Must be a unit vector.

**Comment by Boomer91** [comment]
Ah, I oversaw that. Yes, dir=[1./3., 1./3., 1./3.] works.
Closing
