### ISSUE TITLE
Is changing `MAX_RENDERERS` possible?

### ISSUE THREAD

**Issue by renefritze** [jupyter-widgets/pythreejs#327]
I'm using pythreejs to plot 2D visualizations of data. For a tutorial (sphinx docs via jupyter-sphinx) we have 11 plots. The current limit for renderers from the `RendererPool` is 8. Is there a way for me to change that?
The canvas snapshots for "frozen" renderers currently seem to be entirely black for me. Can you help me finding out why that is?
The tutorial is currently accessible [here](https://gh-docs.pymor.org/jupyter-sphinx/tutorial01.html)

**Comment by vidartf** [comment]
There isn't currently a way to change this limit at run-time, no. Note that the consequence for raising this to high would result in the browser reclaiming entire contexts, making safe recovery next to impossible (as you try to create a new one, another breaks). And while raising the limit in your browser might work, it might not on someone else's computer.

With that being said, I think it is more productive to make the render pool work correctly. Going to the tutorial link you posted, I see all the view ports as black initially, but when mousing over them, they all appear (and no views ever go black again). Is this the same as what you are seeing?

**Comment by renefritze** [comment]
> And while raising the limit in your browser might work, it might not on someone else's computer.

So an underlying problem is that the browser behaviour really isn't "knowable", right? As in even if I know a-priori how much data each context needs there's no way to actually determine the effective maximum number of contexts? 

> Is this the same as what you are seeing?

Exactly. Additionally Safari behaves erratically even after hover. As in, seemingly randomly, shuffles  which plots to load where.



> With that being said, I think it is more productive to make the render pool work correctly.

Sounds good. What would should I do next? I did not see any errors in the browser's dev console on page load. Also Javascript isn't really my forté, but I'm happy to dig in if you can give me some direction.

**Comment by renefritze** [comment]
By setting `webgl_version=1` on the renderer the black box problem disappears for us. Since we're not using anything webgl 2 specific (afaict) this is a good enough workaround for us for now.

**Comment by vidartf** [comment]
Looking at this, I would debug the JS (breakpoints + step-through with browser devtools) to investigate whether or not a call to render the scene is made after the webgl context is created + acquired. If such a call is not made, then we need to sort out our logic to ensure that such a call is always made. If such a call is made, then we need to investigate why the call results in an all-black frame.

Your finding that specifying the webgl version for the renderer is significant should also help inform the debugging.

**Comment by vidartf** [comment]
I think the fix for this is here, so closing: https://github.com/jupyter-widgets/pythreejs/pull/378/files#r882706126
