### ISSUE TITLE
WebGLDataUnion causes DeprecationWarnings

### ISSUE THREAD

**Issue by adriendelsalle** [jupyter-widgets/pythreejs#332]
Hi and thank you for this great project!

Description
--

I'm currently using `WebGLDataUnion` through `BufferAttribute` and I noticed `DeprecationWarning`(s).

_traitlets.py#567_
> DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
 silent = bool(old_value == new_value)

It occurs when updating the `array` attribute of a `BufferAttribute` object with a different size array.

**Note**: it also causes observers to be triggered even when the new and old arrays are identical
``` python
bool(np.r_[10., 40., 30.] == np.r_[10., 40., 30.])
```
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Steps to reproduce
--
``` python
import warnings

from pythreejs import WebGLDataUnion
from traitlets import HasTraits
import numpy as np

warnings.simplefilter("always")

class TestClass(HasTraits):

    array = WebGLDataUnion()


test = TestClass()
test.array = np.array([10., 20., 30.], dtype=np.float32)
test.array = np.array([10., 40., 30.], dtype=np.float32)  # <-- that's ok
test.array = np.array([10., 40.], dtype=np.float32)  # <-- DeprecationWarning
```

Possible fix
--
Overload the `set` method of `DataUnion` in `ipydatawidgets` project:

Use _np.array_equal(old_value, new_value)_ instead of _bool(old_value == new_value)_
``` python
    def set(self, obj, value):
        new_value = self._validate(obj, value)
        try:
            old_value = obj._trait_values[self.name]
        except KeyError:
            old_value = self.default_value

        obj._trait_values[self.name] = new_value
        try:
            silent = np.array_equal(old_value, new_value)
        except:
            # if there is an error in comparing, default to notify
            silent = False
        if silent is not True:
            # we explicitly compare silent to True just in case the equality
            # comparison above returns something other than True/False
            obj._notify_trait(self.name, old_value, new_value)
```

I can make a PR if this fix looks relevant.
Thanks!

**Comment by vidartf** [comment]
Was fixed in linked ipydatawidgets PR.
