### ISSUE TITLE
JupyterLab 3.x "Model not found" error

### ISSUE THREAD

**Issue by FuriouslyCurious** [jupyter-widgets/pythreejs#345]
Heads up for the devs: I am trying out pythreejs examples in latest JupyterLab 3.0 from conda-forge, but unfortunately getting following error message:

`Error displaying widget: model not found`

All packages are installed correctly and jupyter lab extensions including pythreejs are enabled.

**Comment by R7President** [comment]
I have also found the same error

**Comment by vidartf** [comment]
Hi, this package has not been updated to support lab 3 yet (it hopefully will soon). It is also unfortunate that there are no errors or warnings during installation 😞

**Comment by bernhard-42** [comment]
Hi @vidartf 
do you have any ETA for the Jupyterlab 3 support? 
Are you planning for a prebuilt extension? Would be awesome to get rid of the node build step and just use pip/conda
Thanks

**Comment by vidartf** [comment]
Should be released now (with a prebuilt extention). If there are any issues, please open up a new report :)

**Comment by bernhard-42** [comment]
@vidartf The new JupyterLab 3 version of `pythreejs` worked flawlessly for me. 
Great job and thanks a lot!

**Comment by mcejp** [comment]
I'm still getting this with pythreejs 2.3.0. It seems to be related to having many individual meshes (~1000) in a scene.
