### ISSUE TITLE
jupyter-threejs/extension possibly incompatible

### ISSUE THREAD

**Issue by maiermic** [jupyter-widgets/pythreejs#346]
I tried on the Docker Playground using this Dockerfile:

```Dockerfile
FROM jupyter/minimal-notebook

USER $NB_USER

RUN pip install jupyter_contrib_nbextensions && \
    jupyter contrib nbextension install --user && \
    pip install pythreejs
```

The notebook shows in the tab Nbextensions that `jupyter-threejs/extension` is `possibly incompatible` (in the tooltip)
![Screenshot2021-01-0216:40:11](https://user-images.githubusercontent.com/8530117/103460766-47db2f00-4d19-11eb-9f2b-79c3deab604f.png)

The current `latest` version ([jupyter/minimal-notebook:d113a601dbb8](https://hub.docker.com/layers/jupyter/minimal-notebook/d113a601dbb8/images/sha256-83ad06c657e3412fba48d748ed34c7dc3c675cbb45c95333bcd3fe054b7ecb53?context=explore)) of the Docker image has Jupyter Notebook `6.1.5` installed (see [source](https://github.com/jupyter/docker-stacks/blob/d113a601dbb8/base-notebook/Dockerfile#L134-L136)). I also tried older versions (e.g. [jupyter/minimal-notebook:48bd283aaae4](https://hub.docker.com/layers/jupyter/minimal-notebook/48bd283aaae4/images/sha256-baaada52930991a86809b8f83d700791eed450717d3792a6816a184ea99d2fcf?context=explore) with Jupyter Notebook `5.6.*`, see [source](https://github.com/jupyter/docker-stacks/blob/48bd283aaae4/base-notebook/Dockerfile#L90-L92)) and got the same result.

With which Jupyter version is pythreejs compatible? Or is there anything missing in the Docker image/environment?

**Comment by maiermic** [comment]
I guess I was a bit hasty. At least it seems to work.
![Screenshot2021-01-0216:56:16](https://user-images.githubusercontent.com/8530117/103461046-79ed9080-4d1b-11eb-9dd6-75d02ad7fe4d.png)

Nevertheless, anything to worry about the warning that `jupyter-threejs/extension` is `possibly incompatible`?

**Comment by vidartf** [comment]
I don't really know what causes `jupyter_contrib_nbextensions` to list it as "possibly incompatible". It would be better if you took this up with the authors of that project.
