### ISSUE TITLE
Text on top of a Geometry/Mesh

### ISSUE THREAD

**Issue by lfnt3** [jupyter-widgets/pythreejs#358]
Hello,

I have generated multiple meshes from simple "quad" geometries based on Geometry(vertices, faces, colors).
Now I would like to "map" a dedicated text on top of each quad. That text does not come from an image but from a list. So let's say a list of numbers, each one number for one generated mesh.

Is something like this possible with pythreejs?

Thanks!
Thom

**Comment by vidartf** [comment]
You would normally use the `TextTexture` for these purposes: https://pythreejs.readthedocs.io/en/latest/api/textures/TextTexture_autogen.html
