### ISSUE TITLE
Version 2.4.0 does not render any widget

### ISSUE THREAD

**Issue by DonJayamanne** [jupyter-widgets/pythreejs#385]
Installed the latest version 2.4.0 and tested a simple widget an nothing is rendered anymore.
Tested in Jupyter Notebook, Jupyter Lab
Looks like the widget mimetype is not sent back at all, only getting text output.

Sample code
```python
from pythreejs import *
from IPython.display import display
from math import pi

# Reduce repo churn for examples with embedded state:
from pythreejs._example_helper import use_example_model_ids
use_example_model_ids()

BoxGeometry(
    width=5,
    height=10,
    depth=15,
    widthSegments=5,
    heightSegments=10,
    depthSegments=15)
```

**Comment by vidartf** [comment]
I just created a fresh environment where I installed Jupyter Lab and pythreejs 2.4.0, and it works there for me. Could you please provide some more context so I can reproduce? What version of `ipywidgets` are you using? Which version of `jupyterlab` are you using? How did you install pythreejs (pip, conda, other?) etc. etc.

**Comment by vidartf** [comment]
Also useful info: Output of `jupyter lab extension list`

**Comment by vidartf** [comment]
After looking a little closer, I see that *previews* do not work with *ipywidgets 7*.
