### ISSUE TITLE
Right click on scene brings up Jupyter menu as well as translating the camera

### ISSUE THREAD

**Issue by nvaytet** [jupyter-widgets/pythreejs#392]
Doing a right-click on a scene brings up the right-click Jupyter menu, while performing a translation operation on the camera.
![Screenshot at 2022-12-06 12-17-21](https://user-images.githubusercontent.com/39047984/205898156-f6a54413-d9c8-4a07-8d44-37da2d7bc465.png)

As a comparison, doing a right-click on a Matplotlib figure using the `ipympl` backend does not bring up the menu.
It would be nice if the right-click also did not show the Jupyter menu with `pythreejs`.

Thanks for any help!

Versions:
```
- pythreejs                 2.4.1              pyhc268e32_0    conda-forge
- python                    3.9.13          h2660328_0_cpython    conda-forge
- ipympl                    0.9.2              pyhd8ed1ab_0    conda-forge
- jupyter_client            7.4.5              pyhd8ed1ab_0    conda-forge
- jupyter_core              5.0.0            py39hf3d152e_0    conda-forge
- jupyter_server            1.23.2             pyhd8ed1ab_0    conda-forge
- jupyterlab                3.5.0              pyhd8ed1ab_0    conda-forge
- jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
- jupyterlab_server         2.16.3             pyhd8ed1ab_0    conda-forge
- jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
```

**Comment by vidartf** [comment]
Thanks, this was missed in the ipywidgets 8 transition (https://ipywidgets.readthedocs.io/en/stable/migration_guides.html#phosphor-lumino). We are not handling the `contextmenu` event because of this!
