### ISSUE TITLE
Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/pythreejs#395]
I'm trying to support ipyvolume/pythreejs in solara, but I'm getting: "Automatic publicPath is not supported in this browser"

Any pointers where a change happened in pythreejs where this changed?

**Comment by maartenbreddels** [comment]
Hmm, also seeing this in the (classic) notebook now. Starting from a new virtual env, pythreejs doesn't seem to work (2.4.1)

**Comment by vidartf** [comment]
I don't think any change was made in pythreejs, but I think a change was recommended? https://ipywidgets.readthedocs.io/en/stable/migration_guides.html#updating-the-webpack-publicpath-configuration  Maybe it will work with that?

**Comment by vidartf** [comment]
This should be fixed in 2.4.2 that I just pushed to PyPI. Please try it and see if it resolves the issue.

**Comment by maartenbreddels** [comment]
Yes, thanks a lot @vidartf !
